/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template fileReader, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.LibroGestion;
import Controlador.Vaciar;

/**
 *
 * @author
 */
public class IngresarLibro extends javax.swing.JFrame {
    LibroGestion book = new LibroGestion();
    Vaciar validation = new Vaciar();
    LibroAdmi frmProviderMenu = new LibroAdmi();

    /**
     * Creates new form FrmProvider
     */
    public IngresarLibro() {
        initComponents();
        this.setTitle("Ingresar libro");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl = new javax.swing.JPanel();
        jlbName = new javax.swing.JLabel();
        jlbLastName = new javax.swing.JLabel();
        jlbCellphone = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        jlbCedula = new javax.swing.JLabel();
        jlbCreateProviderTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEdicion = new javax.swing.JTextField();
        jlbCellphone1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jlbCellphone2 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jlbOnlyNumbersPhoneNumber = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnEmptyFields = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Provider");

        pnl.setPreferredSize(new java.awt.Dimension(705, 465));
        pnl.setLayout(null);

        jlbName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/uta/purchaseandsalesrecordgui/images/name.png"))); // NOI18N
        jlbName.setText("Autor");
        pnl.add(jlbName);
        jlbName.setBounds(30, 150, 90, 40);

        jlbLastName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/uta/purchaseandsalesrecordgui/images/libro-abierto.png"))); // NOI18N
        jlbLastName.setText("Titulo");
        pnl.add(jlbLastName);
        jlbLastName.setBounds(30, 210, 100, 40);

        jlbCellphone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/uta/purchaseandsalesrecordgui/images/libro-abierto.png"))); // NOI18N
        jlbCellphone.setText("Cantidad");
        pnl.add(jlbCellphone);
        jlbCellphone.setBounds(30, 360, 120, 40);

        txtId.setToolTipText("Enter only numbers");
        pnl.add(txtId);
        txtId.setBounds(160, 110, 150, 30);

        txtAutor.setToolTipText("Don't use special characteres");
        pnl.add(txtAutor);
        txtAutor.setBounds(160, 160, 150, 30);

        txtTitulo.setToolTipText("Don't use special characteres");
        pnl.add(txtTitulo);
        txtTitulo.setBounds(160, 210, 150, 30);

        txtCategoria.setToolTipText("Enter only 10 numbers");
        txtCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCategoriaKeyPressed(evt);
            }
        });
        pnl.add(txtCategoria);
        txtCategoria.setBounds(160, 310, 150, 30);

        jlbCedula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/uta/purchaseandsalesrecordgui/images/libro-abierto.png"))); // NOI18N
        jlbCedula.setText("ID:");
        pnl.add(jlbCedula);
        jlbCedula.setBounds(30, 100, 90, 40);

        jlbCreateProviderTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/uta/purchaseandsalesrecordgui/images/createProviderBtn.png"))); // NOI18N
        jlbCreateProviderTitle.setText("Registrar un libro");
        pnl.add(jlbCreateProviderTitle);
        jlbCreateProviderTitle.setBounds(110, 0, 180, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/uta/purchaseandsalesrecordgui/images/libro-abierto.png"))); // NOI18N
        jLabel1.setText("Edicion");
        pnl.add(jLabel1);
        jLabel1.setBounds(30, 260, 100, 40);
        pnl.add(txtEdicion);
        txtEdicion.setBounds(160, 260, 150, 30);

        jlbCellphone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/uta/purchaseandsalesrecordgui/images/libro-abierto.png"))); // NOI18N
        jlbCellphone1.setText("Categoria");
        pnl.add(jlbCellphone1);
        jlbCellphone1.setBounds(30, 310, 110, 40);

        txtCantidad.setToolTipText("Enter only 10 numbers");
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
        });
        pnl.add(txtCantidad);
        txtCantidad.setBounds(160, 360, 150, 30);

        jlbCellphone2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/uta/purchaseandsalesrecordgui/images/dolar.png"))); // NOI18N
        jlbCellphone2.setText("Precio");
        pnl.add(jlbCellphone2);
        jlbCellphone2.setBounds(30, 410, 120, 30);

        txtPrecio.setToolTipText("Enter only 10 numbers");
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioKeyPressed(evt);
            }
        });
        pnl.add(txtPrecio);
        txtPrecio.setBounds(160, 410, 150, 30);

        jlbOnlyNumbersPhoneNumber.setForeground(new java.awt.Color(255, 0, 0));

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEmptyFields.setText("Vaciar campos");
        btnEmptyFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmptyFieldsActionPerformed(evt);
            }
        });

        btnReturn.setText("Regresar");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEmptyFields, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)
                        .addComponent(jlbOnlyNumbersPhoneNumber))
                    .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbOnlyNumbersPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSave)
                        .addComponent(btnEmptyFields)
                        .addComponent(btnReturn)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        frmProviderMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnEmptyFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmptyFieldsActionPerformed
        validation.emptyFields(evt, pnl, jlbOnlyNumbersPhoneNumber);
    }//GEN-LAST:event_btnEmptyFieldsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        book.crearLibro(txtId, txtAutor, txtTitulo, txtEdicion, txtCategoria, txtPrecio, txtCantidad, rootPane, jlbOnlyNumbersPhoneNumber);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoriaKeyPressed

    }//GEN-LAST:event_txtCategoriaKeyPressed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyPressed

    private void txtPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmptyFields;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlbCedula;
    private javax.swing.JLabel jlbCellphone;
    private javax.swing.JLabel jlbCellphone1;
    private javax.swing.JLabel jlbCellphone2;
    private javax.swing.JLabel jlbCreateProviderTitle;
    private javax.swing.JLabel jlbLastName;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbOnlyNumbersPhoneNumber;
    private javax.swing.JPanel pnl;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
